### ISSUE TITLE
The relevant parts of the component should be exposed as stylable parts

### ISSUE THREAD

**Issue by johannesh2** [vaadin/vaadin-app-layout#3]
- It is possible to style the “navigation bar” (containing the branding and menu areas)
- It is possible to style the menu area
- It is possible to style the branding area
- It is possible to style the content area

**Comment by jouni** [comment]
For disambiguation, I assume this means that there should be wrapper elements for the corresponding areas/slots defined here, with a `part` attribute with the same name as the area/slot.

I don’t necessarily think the branding, menu and content area’s need to be stylable, as the developer can style the contents inside them freely. We don’t yet have a use case for styling the actual slots/slot containers. Might be wiser to wait for user feedback before adding those. But, that said, adding those is trivial and might make some developers really happy since their edge case can be covered out-of-the-box.
