### ISSUE TITLE
iPhone landscape doesn’t use full width (doesn’t go into notch area in iPhone X)

### ISSUE THREAD

**Issue by alvarezguille** [vaadin/vaadin-app-layout#70]

**Comment by jouni** [comment]
This can’t be controlled by the component (technically, we could manipulate the meta tags of the app from the component, but that feels wrong). We need to document how to achieve it.

Basically, you need to use `<meta name="viewport" content="viewport-fit=cover">`.

**Comment by DiegoCardoso** [comment]
I give this a quick test and on iPhone simulator, it made it work as desktop because it changed the size of the page (for instance, on iPhone X it resulted on width as `980px` and height as `1659px`). I tried adding `-webkit-min-device-pixel-ratio: 2` to the media queries (for `overlay` and `touch-optimized`), but then the result looked not good too:
![Screenshot 2019-04-23 at 14.12.31.png](https://images.zenhubusercontent.com/5afd1bfa4b5806bc2bd382d1/85ed1f81-e7b2-4f2e-b8bc-d672652deeed)

**Comment by jouni** [comment]
In addition to `viewport-fit=cover` you also need to add `width=device-width` as usual, to make the browser render the page using the native screen width.

So all in all, this should be the meta tag that we use in our demos (and probably should promote in the docs as well):

`<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">`

More info about the viewport meta tag: https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag

**Comment by alvarezguille** [comment]
Let's mention it in docs as well yes
